"""Shared constants for sonic-side data collection."""

RS_VIEW_CAMERA_HEIGHT = 480
RS_VIEW_CAMERA_WIDTH = 640

BUCKET_BASE_PATH = "GearRawDataLeRobotV0"

SONIC_TOKEN_STATE_DIM = 64
SONIC_ENCODER_INPUT_DIM = 1762
SONIC_DECODER_INPUT_DIM = 994
